/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Rocket.gltf --types 
Author: clarence365 (https://sketchfab.com/clarence365)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/relativity-space-terran-1-b1a23b822e8a431babe584a3c4cae052
Title: Relativity Space Terran 1
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Common } from "./Common";
import { Group, Mesh, MeshStandardMaterial } from "three";
import { useFrame } from "@react-three/fiber";
import { SpectrumProps } from "@/types";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: Mesh;
    Object_5: Mesh;
    Object_6: Mesh;
    Object_7: Mesh;
    Object_8: Mesh;
    Object_9: Mesh;
    Object_10: Mesh;
    Object_11: Mesh;
    Object_12: Mesh;
    Object_13: Mesh;
    Object_14: Mesh;
    Object_15: Mesh;
    Object_16: Mesh;
    Object_17: Mesh;
    Object_18: Mesh;
    Object_19: Mesh;
    Object_20: Mesh;
    Object_21: Mesh;
    Object_22: Mesh;
    Object_23: Mesh;
    Object_25: Mesh;
    Object_26: Mesh;
    Object_27: Mesh;
    Object_28: Mesh;
    Object_29: Mesh;
    Object_30: Mesh;
    Object_31: Mesh;
    Object_32: Mesh;
    Object_33: Mesh;
    Object_34: Mesh;
    Object_35: Mesh;
    Object_36: Mesh;
    Object_37: Mesh;
    Object_38: Mesh;
    Object_39: Mesh;
    Object_40: Mesh;
    Object_42: Mesh;
    Object_44: Mesh;
  };
  materials: {
    ["Material.001"]: MeshStandardMaterial;
    ["Material.002"]: MeshStandardMaterial;
    ["Material.003"]: MeshStandardMaterial;
    ["Material.004"]: MeshStandardMaterial;
    ["Material.005"]: MeshStandardMaterial;
    ["Material.006"]: MeshStandardMaterial;
    ["Material.007"]: MeshStandardMaterial;
    ["Material.008"]: MeshStandardMaterial;
    ["Material.009"]: MeshStandardMaterial;
    ["Material.010"]: MeshStandardMaterial;
    ["Material.011"]: MeshStandardMaterial;
    ["Material.017"]: MeshStandardMaterial;
    ["Material.012"]: MeshStandardMaterial;
    ["Material.013"]: MeshStandardMaterial;
    ["Material.014"]: MeshStandardMaterial;
    ["Material.015"]: MeshStandardMaterial;
    ["Material.016"]: MeshStandardMaterial;
    ["Material.018"]: MeshStandardMaterial;
    ["Material.027"]: MeshStandardMaterial;
    ["Material.028"]: MeshStandardMaterial;
    ["Material.019"]: MeshStandardMaterial;
    ["Material.020"]: MeshStandardMaterial;
    ["Material.021"]: MeshStandardMaterial;
    ["Material.022"]: MeshStandardMaterial;
    ["Material.023"]: MeshStandardMaterial;
    ["Material.024"]: MeshStandardMaterial;
    ["Material.025"]: MeshStandardMaterial;
    ["Material.026"]: MeshStandardMaterial;
    ["Material.032"]: MeshStandardMaterial;
    ["Material.031"]: MeshStandardMaterial;
    ["Material.040"]: MeshStandardMaterial;
  };
};

export function Rocket({ data }: { data: SpectrumProps }) {
  const { nodes, materials } = useGLTF("/Rocket.gltf") as GLTFResult;

  const ref = useRef<Group>(null);
  useFrame((state, delta) => {
    if (!ref.current) {
      return;
    }
    if ("IsActionRequired" in data ? data.IsActionRequired : false) {
      const flashColor =
        state.clock.elapsedTime % 1 < 0.5 ? "#FF0000" : "white";
      materials["Material.001"].color.set(flashColor);
      materials["Material.010"].color.set(flashColor);
      ref.current.rotation.y += delta * 6;
    } else {
      materials["Material.001"].color.set("white");
      materials["Material.010"].color.set("white");
    }
    ref.current.rotation.y += delta * 2;
  });

  return (
    <group ref={ref} position={[0, -0.28, 0]} scale={0.1} dispose={null}>
      <Common />
      <group position={[0, 1.319, 0]} scale={0.343}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          // material-color={"red"}
          geometry={nodes.Object_6.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          material-color={"#B0B0B0"}
          geometry={nodes.Object_9.geometry}
          // material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials["Material.028"]}
        />
      </group>

      <group position={[0, 7.783, 0]} scale={0.343}>
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials["Material.040"]}
        />
      </group>
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials["Material.001"]}
        position={[0, 8.001, 0]}
        scale={0.343}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials["Material.001"]}
        position={[0, 7.998, 0]}
        scale={0.343}
      />
    </group>
  );
}

useGLTF.preload("/Rocket.gltf");
